config/routes.rb
Rails.application.routes.draw do

scope ":locale",locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :users, controllers: { users: 'users' }
  resources :libraries
  resources :rooms
  resources :libraries do 
  resources :rooms
  end
  resources :reservations do
    get "update_table" , on: :collection
  end     
  resources :users 
  root to: 'reservations#index'
end

match '*path', to: redirect {"/#{I18n.default_locale}/%{path}"}, via: :get
match '*path', to: redirect {"/#{I18n.default_locale}/%{path}"}, via: :post
match '', :via => [:get], to: redirect("/#{I18n.default_locale}")
match '', :via => [:post], to: redirect("/#{I18n.default_locale}")

end

app/models/library.rb
class Library < ActiveRecord::Base
	has_many :reservations, dependent: :destroy
	has_many :rooms, dependent: :destroy
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
	@user = current_user
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)
	
    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: I18n.t('views.libraries.libmsg1') }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: I18n.t('views.libraries.libmsg2') }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: I18n.t('views.libraries.libmsg3') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:lib_name)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_for(@library) do |f| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> <%= I18n.t('views.libraries.libmsg4') %>:</h2>

      <ul>
      <% @library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lib_name %><br>
    <%= f.text_field :lib_name %>
  </div>
  <div class="actions">
    <%= f.submit I18n.t('views.libraries.createlibrary') %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1><%= I18n.t('views.libraries.editlibrary') %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.show'), @library %> |
<%= link_to I18n.t('views.back'), libraries_path %>

app/views/libraries/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= I18n.t('views.libraries.index.listlibrary') %></h1>

<table>
  <thead>
    <tr>
      <th><%= I18n.t('views.libraries.libname') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.lib_name %></td>
        <td><%= link_to I18n.t('views.show'), library %></td>
        <td><%= link_to I18n.t('views.edit'), edit_library_path(library) %></td>
        <td><%= link_to I18n.t('views.destroy'), library, method: :delete, data: { confirm: I18n.t('views.sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to I18n.t('views.libraries.newlibrary'), new_library_path %>

app/views/libraries/new.html.erb
<h1><%= I18n.t('views.libraries.newlibrary') %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.back'), libraries_path %>

app/views/libraries/show.html.erb
  
  
</div>



<p id="notice"><%= notice %></p>

<p>
  <strong><%= I18n.t('views.libraries.libname') %>:</strong>
  <%= @library.lib_name %>
</p>

<h2 style="margin-left:5%;"> <%= I18n.t('views.libraries.rooms') %> </h2>
<div id = "comments">
  <% @library.rooms.each do |room| %>
    <%= div_for room do %>
  <p>   
    <%= h(room.id) %>   
    <div class="linksdiv" style="font-color:white"><%= link_to I18n.t('views.edit'), edit_library_room_path(room ,id:room.id) %></div>  
  </p>
<% end %>
  <% end %>
</div>

<div id = "comments">
<%= form_for([@library, Room.new]) do |f| %>
<p> <%= f.label :id, I18n.t('views.rooms.newroom') %> <br />    
</p>
  <p>
    <%= f.label :seating_capacity %><br>
    <%= f.number_field :seating_capacity %>
  </p>
  <p>
    <%= f.label :amenities %><br>
    <%= f.text_area :amenities %></p>
 <p>
    <%= f.label :roomtype %><br>
    <%= f.text_field :roomtype %>
 </p>
<p> <%= f.submit I18n.t('views.rooms.addroom') %> </p>
<%= link_to I18n.t('views.edit'), edit_library_path(@library) %> |
<%= link_to I18n.t('views.back'), libraries_path %>
<% end %></div>