config/routes.rb
Rails.application.routes.draw do

scope ":locale",locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :users, controllers: { users: 'users' }
  resources :libraries
  resources :rooms
  resources :libraries do 
  resources :rooms
  end
  resources :reservations do
    get "update_table" , on: :collection
  end     
  resources :users 
  root to: 'reservations#index'
end

match '*path', to: redirect {"/#{I18n.default_locale}/%{path}"}, via: :get
match '*path', to: redirect {"/#{I18n.default_locale}/%{path}"}, via: :post
match '', :via => [:get], to: redirect("/#{I18n.default_locale}")
match '', :via => [:post], to: redirect("/#{I18n.default_locale}")

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :room
  belongs_to :library
  belongs_to :user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
  @reservations = Reservation.all
  @date = Date.today
	setlibrary
  setlist
 
 
end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  def update_table

  @reservations = Reservation.all
  setlibrary
  
  #@date = Date.parse(params[:selected_date] )
  @date =  DateTime.strptime( params[:selected_date], '%m/%d/%Y')
  setlist
  #binding.pry
  respond_to do |format|
    format.js
    end
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    send_text_message( @reservation.phone , @reservation.start_time , @reservation.end_time)
    

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: I18n.t('views.reservations.resmsg1') }

        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: I18n.t('views.reservations.resmsg2') }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end


  def send_text_message(phonenumber, start_time, end_time )
    number_to_send_to = phonenumber    #params[:number_to_send_to]
    starttime = start_time.to_s
    endtime  =  end_time.to_s
    twilio_sid = "ACc629aae0d6938192ad6ec3d049a31504"
    twilio_token = "37fbc61fab94fc1a6244b7ca3b859a13"
    twilio_phone_number = "2184607910"

    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token

    @twilio_client.account.sms.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => number_to_send_to,
      :body => "Your  reservation from " + starttime + " to " + endtime + " is confirmed !"
    )
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: I18n.t('views.reservations.resmsg3') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:booking_id, :room_id, :library_id, :user_id, :start_time, :end_time , :phone ,:title, :description)
    end
    def setlibrary
      if params[:id].present?
      @library = Library.find(params[:id])
      else
      @library = Library.find(1)
      end     
    end

    def setlist
     
      @list = []
    for i in 0..6
      for k in @library.rooms   
         for j in 8..19 
        @availableRooms = Reservation.select(%q{count(id) as count2}).where("start_time <= ?", DateTime.new((@date+i.days).strftime('%Y').
          to_i, (@date+i.days).strftime('%m').to_i, (@date+i.days).strftime('%d').to_i, j, 0, 0)).where("end_time > ?", DateTime.new((@date+i.days).strftime('%Y').
          to_i, (@date+i.days).strftime('%m').to_i, (@date+i.days).strftime('%d').to_i, j, 0, 0)).where(:room_id => k.id)
          @list << @availableRooms[0]
          end
      end
    end
    
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_date_table.html.erb
<% if (@library.rooms.length ==0 ) %>
 <label style="text-align:center;font-size:50px;margin-top:10%;display:inline-block;color:gold;margin-left:5%;"  >No Rooms for Selected Library </label>
<% else %>
<% (0..6).each do |j| %>
 


<table class="timestable">
  <thead>
	<tr>
		<th style="width:13%;color:chartreuse;"><%= I18n.t('views.reservations.index.date') %>: <%= (@date + j.days).strftime('%m-%d-%Y') %></th>	

		<% startdate = @date + j.days
		interval = 60
		formatstr = '%H:%M' %>

		<% (8..19).map{|offset| startdate + (offset * interval).minutes }.map{|date| date.strftime(formatstr)}.each do |k|  %>
			<th><%= k %></th>
		<% end %>
	</tr>
  </thead>
  <tbody>  	
  	<% var = 0 
	@library.rooms.each do |room| 
		var = var+1 %>
	  <tr>		
		 <td style="width:13%;"><%= I18n.t('views.room') %> <%= room.id%> (<%= room.seating_capacity%> <%= I18n.t('views.maximum')%>)</td>
		 <% (8..19).each do |i| %>
				<%if current_user %>
				<td><%= form_tag(new_reservation_path, :method => :get) do |f| %>
					<%= hidden_field_tag 'libid', room.library_id %>	
					<%= hidden_field_tag 'roomid', room.id %>
					<%= hidden_field_tag 'starttime', startdate +  i.hours %>	

					<%= hidden_field_tag 'endtime', startdate + (i+1).hours %>
					<%= hidden_field_tag 'dateres', startdate %>									
					<% x = 0	
					t = var - 1	
					k = @library.rooms.size			
					x = (i+ (12*t- 8)) + j * k * (12) %>										 					
					<% if (@list[x].count2 > 0 ) %>
					<%= submit_tag ' ', :disabled =>  true %>
					<% else %>
					<%= submit_tag ' ' %>					
					<% end %>										
				<% end %></td>
				<% else %>
				<td><%= form_tag(new_user_session_path) do |f| %>
					<%= hidden_field_tag 'libid', room.library_id %>									
					<%= submit_tag ' ' %>
				<% end %></td>	
				<% end %>
		<% end %>
	  </tr>	
	<% end %>
  </tbody>
</table>
<% end %>
<% end %>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> <%= I18n.t('views.reservations.resmsg4') %>:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :library_id %><br>
    <%= f.text_field :library_id,:readonly => true, value: params[:libid] %>
  </div>
  <div class="field">
    <%= f.label :room_id %><br>
    <%= f.text_field :room_id,:readonly => true, value: params[:roomid] %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>     
	<%= f.datetime_select(:start_time, :default => { :hour => DateTime.parse(params[:starttime]).strftime('%H'), :minute => DateTime.parse(params[:starttime]).strftime('%M'), 
                                                     :day => DateTime.parse(params[:dateres]).strftime('%d')	}) %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select(:end_time, :default => { :hour => DateTime.parse(params[:endtime]).strftime('%H'), :minute => DateTime.parse(params[:starttime]).strftime('%M'),
                                                   :day => DateTime.parse(params[:dateres]).strftime('%d')	}) %>
  </div>

<div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>


  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit I18n.t('views.reservations.createreservation') %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1><%= I18n.t('views.reservations.editreserve') %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.show'), @reservation %> |
<%= link_to I18n.t('views.back'), reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="display:inline-block;"><%= I18n.t('views.reservations.index.reserve') %></h1>
<div class="dispdiv" style="display:inline-block;font-size:2em;margin-left:10%;">
<p><%= I18n.t('views.reservations.index.date') %>:
<input type="text" id="datepicker" onchange="updatedate_table()"></p>


<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">

<script>
     var time = new Date().getTime();
   
     
     $(document.body).bind("mousemove keypress", function(e) {
         time = new Date().getTime();
     });

     
     function refresh() {
         if(new Date().getTime() - time >= 20000) {
             window.location.reload(true);
             //document.getElementById('daterefresh').innerHTML  =   'page refreshed at' + ' ' + new Date().getTime();
            //updatedate_table();
            //document.getElementById('daterefresh').innerHTML  =   'Page refreshed at' + ' ' + new Date().getTime() - time + 'ago' ;
          // alert("page refreshed");
          }
         else 
             setTimeout(refresh, 20000);
     }

     setTimeout(refresh, 20000);
</script>

<script type="text/javascript">
var currentTime = new Date();
window.onload=function() {
document.getElementById("datepicker").value = currentTime.getDate() + "/" + (currentTime.getMonth()+1) + "/" + currentTime.getFullYear();
var today = new Date();
var h = today.getHours();
var m = today.getMinutes();
var s = today.getSeconds();

document.getElementById('daterefresh').innerHTML  =   'Page refreshed at' + ' ' +  h + ":" + m + ":" + s + "(H:M:S)";

};

function getdate() {

return document.getElementById("datepicker").value ;

}

function updatedate_table()
{
	$.ajax({url: '<%= j update_table_reservations_path %>' , data: {selected_date: getdate() }})
}


</script>

  <script>
  $(function() {
    $( "#datepicker" ).datepicker();
    var date = $("#datepicker").text ;
  });
  </script>
<label><%= I18n.t('views.reservations.index.select') %>:</label>
<% Library.all.each do |library| %>
	<%= form_tag(root_path, :method => :get) do |f| %>
		<%= hidden_field_tag 'id', library.id %>
		<%= submit_tag library.lib_name	%>
	<% end %>
	<% end %>	
</div>




<div id="dates_table">
<%= render 'date_table' %>
</div>
<style>
#daterefresh{
  float: right;
  color: deepskyblue;
  font-size: 1.5em ;
} 
</style>
<br/>
<br/>
<div>
<label id="daterefresh"  text="test"/>
<div>
<br>

app/views/reservations/new.html.erb
<h1><%= I18n.t('views.reservations.newreserve') %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.back'), reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= I18n.t('views.reservations.booking') %>:</strong>
  <%= @reservation.booking_id %>
</p>

<p>
  <strong><%= I18n.t('views.reservations.room1') %>:</strong>
  <%= @reservation.room %>
</p>

<p>
  <strong><%= I18n.t('views.reservations.library1') %>:</strong>
  <%= @reservation.library %>
</p>

<p>
  <strong><%= I18n.t('views.reservations.user1') %>:</strong>
  <%= @reservation.user %>
</p>

<p>
  <strong><%= I18n.t('views.reservations.stime') %>:</strong>
  <%= @reservation.start_time %>
</p>

<p>
  <strong><%= I18n.t('views.reservations.etime') %>:</strong>
  <%= @reservation.end_time %>
</p>

<p>
  <strong><%= I18n.t('views.reservations.title') %>:</strong>
  <%= @reservation.title %>
</p>

<p>
  <strong><%= I18n.t('views.reservations.description') %>:</strong>
  <%= @reservation.description %>
</p>

<%= link_to I18n.t('views.edit'), edit_reservation_path(@reservation) %> |
<%= link_to I18n.t('views.back'), reservations_path %>

app/views/reservations/update_table.js.erb
$('#dates_table').html('<%= j render "date_table" %>');