config/routes.rb
Rails.application.routes.draw do

scope ":locale",locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :users, controllers: { users: 'users' }
  resources :libraries
  resources :rooms
  resources :libraries do 
  resources :rooms
  end
  resources :reservations do
    get "update_table" , on: :collection
  end     
  resources :users 
  root to: 'reservations#index'
end

match '*path', to: redirect {"/#{I18n.default_locale}/%{path}"}, via: :get
match '*path', to: redirect {"/#{I18n.default_locale}/%{path}"}, via: :post
match '', :via => [:get], to: redirect("/#{I18n.default_locale}")
match '', :via => [:post], to: redirect("/#{I18n.default_locale}")

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :library
  has_many :reservations, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @library = Library.find(params[:library_id])
    @room = @library.rooms.create(room_params)	

    respond_to do |format|
      if @room.save
        format.html { redirect_to @library, notice: I18n.t('views.rooms.roommsg1') }
        format.json { render :show, status: :created, location: @room }
		format.js
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: I18n.t('views.rooms.roommsg2') }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to library_rooms_url, notice: I18n.t('views.rooms.roommsg3') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:library_id, :seating_capacity, :amenities, :roomtype)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room, library_id: :library_id) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> <%= I18n.t('views.rooms.roommsg4') %>:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :library_id %><br>
    <%= f.collection_select(:library_id, Library.all, :id, :lib_name) %>
  </div>
  <div class="field">
    <%= f.label :seating_capacity %><br>
    <%= f.number_field :seating_capacity %>
  </div>
  <div class="field">
    <%= f.label :amenities %><br>
    <%= f.text_area :amenities %>
  </div>
  <div class="field">
    <%= f.label :roomtype %><br>
    <%= f.text_field :roomtype %>
  </div>
  <div class="actions">
    <%= f.submit I18n.t('views.rooms.createroom')%>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1><%= I18n.t('views.rooms.editroom') %></h1>

<%= render 'form' %>

<td><%= link_to I18n.t('views.show'), library_room_path(@room, id: @room.id) %></td> |
<%= link_to I18n.t('views.back'), library_rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= I18n.t('views.rooms.index.listroom') %></h1>

<table>
  <thead>
    <tr>
      <th><%= I18n.t('views.rooms.library') %></th>
      <th><%= I18n.t('views.rooms.seating') %></th>
      <th><%= I18n.t('views.rooms.amenities') %></th>
      <th><%= I18n.t('views.rooms.roomtype') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.library %></td>
        <td><%= room.seating_capacity %></td>
        <td><%= room.amenities %></td>
        <td><%= room.roomtype %></td>
        <td><%= link_to I18n.t('views.show'), library_room_path(room, id: room.id) %></td>
        <td><%= link_to I18n.t('views.edit'), edit_library_room_path(room, id: room.id) %></td>
        <td><%= link_to I18n.t('views.destroy'), library_room_path(room, id: room.id), method: :delete, data: { confirm: I18n.t('views.sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to I18n.t('views.rooms.newroom'), new_library_room_path %>

app/views/rooms/new.html.erb
<h1><%= I18n.t('views.rooms.newroom') %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.back'), library_rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= I18n.t('views.rooms.library') %>:</strong>
  <%= @room.library %>
</p>

<p>
  <strong><%= I18n.t('views.rooms.seating') %>:</strong>
  <%= @room.seating_capacity %>
</p>

<p>
  <strong><%= I18n.t('views.rooms.amenities') %>:</strong>
  <%= @room.amenities %>
</p>

<p>
  <strong><%= I18n.t('views.rooms.roomtype') %>:</strong>
  <%= @room.roomtype %>
</p>

<%= link_to I18n.t('views.edit'), edit_library_room_path(@room, id: @room.id) %> |
<%= link_to I18n.t('views.back'), library_rooms_path(library_id: @room.library.id) %>